export const SIGN_IN = "SING_IN";
export const SIGN_OUT = "SING_OUT";
export const FETCH_USER = "FETCH_USER";
export const FETCH_ALL_CLIENTS = "FETCH_ALL_CLIENTS";
export const FETCH_CLIENT_BY_SEARCH = "FETCH_CLIENT_BY_SEARCH";
export const FETCH_CLIENT_BY_CLID = "FETCH_CLIENT_BY_CLID";
export const FETCH_ALL_EMPLOYEE = "FETCH_ALL_EMPLOYEE";
